[package]
name = "hifa"
version = "0.0.1"
license = "MIT OR Apache-2.0"
homepage = "https://hifa-lang.org"
repository = "https://github.com/hifa-lang/hifa.git"
description = "Hifa Language"
readme = "README.md"
edition = "2021"

[dependencies]
